import './globals.css'
import { Jost } from 'next/font/google'
import { Header } from '@/app/ui/Header';
import { Footer } from './ui/Footer';

const jost = Jost({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${jost.className }`}>
        <div className="max-w-[1110px] mx-auto sm:px-10 md:px-0">
          <Header />
          {children}
        </div>
        <Footer cta={true} />
      </body>
    </html>
  )
}
