import './globals.css'
import { Jost } from 'next/font/google'
import { Header } from '@/app/ui/Header';

const jost = Jost({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${jost.className } max-w-[1110px] mx-auto sm:px-10`}>
        <Header />
        {children}
      </body>
    </html>
  )
}
